---
package_manifest: "{{ lookup('file', playbook_dir ~ '/vars/package-manifest.json') | from_json }}"

######################################
### giftpilz0.general.git

git_config_system:
  - key: init.defaultBranch
    value: main
  - key: core.editor
    value: hx
  - key: core.whitespace
    value: fix,-indent-with-non-tab,trailing-space,cr-at-eol
  - key: color.ui
    value: auto
  - key: gpg.program
    value: /usr/bin/gpg

git_config:
  - key: user.name
    value: ""
    scope: global
  - key: user.email
    value: ""
    scope: global

######################################
### giftpilz0.general.timezone

timezone_timezone: Europe/Berlin

######################################
### giftpilz0.general.packages

packages_python_package:
  - pre-commit

packages_flatpak_repos: "{{ package_manifest.flatpak_repos }}"
packages_flatpak_repos_remove: "{{ package_manifest.flatpak_repos_remove }}"
packages_flatpak_package: "{{ package_manifest.flatpak_packages }}"

######################################
### giftpilz0.general.firewalld

firewalld_zones_define:
  - zone: work
    source: 192.168.10.0/24
    target: DROP

firewalld_rules_services:
  - service: ssh
    zone: work
    state: disabled

######################################
### giftpilz0.general.user

admin_group: "{{ 'wheel' if ansible_os_family == 'RedHat' else 'sudo' }}"

user_key_target_users: []

user:
  - user_username: "{{ user_username }}"
    user_groups:
      - "{{ admin_group }}"
      - "{{ user_username }}"
    user_home: true
    user_shell: "/bin/bash"
    user_comment: "{{ user_username }}"
    user_install_key_to_targets: false
    user_sudo_pwless: false
    user_state: present
    user_password: "{{ user_password }}"
    user_pub:
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOAhl7NUVzPjYfk/rB+dS0i6wDPkB5EtlZSfVwGdrWsg"
