---
######################################
### giftpilz0.general.packages

packages_python_package:
  - pre-commit

packages_flatpak_repos:
  - name: flathub
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    state: present

packages_flatpak_repos_remove:
  - fedora
  - fedora-testing

packages_flatpak_package:
  - name: dev.zed.Zed
    state: present
    remote: flathub
  - name: io.github.kolunmi.Bazaar
    state: present
    remote: flathub
