FROM scratch AS ctx

COPY ublue-niri/build_files /build
COPY ublue-niri/system_files /files
COPY ublue-niri/cosign.pub /files/etc/pki/containers/ublue-niri.pub
# COPY --from=ghcr.io/ublue-os/brew:latest /system_files /files
COPY Justfile /Justfile
COPY ansible /ansible

FROM quay.io/fedora/fedora-bootc:43

ENV ANSIBLE_USER=root
ENV INVENTORY=inventory/bootc

RUN --mount=type=bind,from=ctx,source=/,target=/ctx \
    --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/tmp \
    --mount=type=cache,dst=/var/cache/libdnf5 \
    /ctx/build/00-base.sh

RUN --mount=type=bind,from=ctx,source=/,target=/ctx \
    --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/tmp \
    --mount=type=cache,dst=/var/cache/libdnf5 \
    /ctx/build/01-dotfiles.sh

RUN --mount=type=bind,from=ctx,source=/,target=/ctx \
    --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/tmp \
    --mount=type=cache,dst=/var/cache/libdnf5 \
    /ctx/build/99-cleanup.sh

RUN rm -rf /var/* && mkdir /var/tmp && bootc container lint
