source $HOME/.config/vim/bundles.vim
source $HOME/.config/vim/settings.vim
source $HOME/.config/vim/map.vim
source $HOME/.config/vim/plugins.vim
source $HOME/.config/vim/functions.vim
source $HOME/.config/vim/autocmd.vim
