# https://github.com/Abhra00/Matuprland

[config]

# Hyprlock
[templates.hyprlock]
input_path = '~/.config/matugen/templates/hyprlock.conf'
output_path = '~/.config/hypr/matugen/colors.conf'

# Sway
[templates.sway]
input_path = '~/.config/matugen/templates/sway'
output_path = '~/.config/sway/matugen/colors'
post_hook = 'swaymsg reload'

# Wofi
[templates.wofi]
input_path = '~/.config/matugen/templates/common.css'
output_path = '~/.config/wofi/matugen/colors.css'

# Swaync
[templates.swaync]
input_path = '~/.config/matugen/templates/common.css'
output_path = '~/.config/swaync/matugen/colors.css'
post_hook = 'swaync-client -rs'

# Gtk3
[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk.css'
output_path = '~/.config/gtk-3.0/gtk.css'

# GTk4
[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk.css'
output_path = '~/.config/gtk-4.0/gtk.css'

# Kitty
[templates.kitty]
input_path = '~/.config/matugen/templates/kitty.conf'
output_path = '~/.config/kitty/matugen/colors.conf'

# EWW
[templates.eww]
input_path = '~/.config/matugen/templates/common.scss'
output_path = '~/.config/eww/scss/matugen/colors.scss'
