---
######################################
### giftpilz0.general.packages

packages_additional_package:
  - "@base-graphical" # meta
  - "@firefox"
  - "@fonts"
  - "@hardware-support"
  - "@libreoffice"
  - "@multimedia"
  - "@networkmanager-submodules"
  - "@printing"
  - langpacks-en # langpacks
  - langpacks-de
  - ansible # misc
  - audit
  - bolt
  - distribution-gpg-keys
  - firewalld
  - flatpak
  - fprintd
  - fprintd-pam
  - git-core
  - gitui
  - gnome-disk-utility
  - gum
  - gvfs-archive
  - gvfs-mtp
  - gvfs-nfs
  - gvfs-smb
  - helix
  - htop
  - just
  - keepassxc
  - kernel-modules-extra
  - nautilus
  - NetworkManager-openconnect
  - NetworkManager-tui
  - nmap
  - pcsc-lite
  - podman
  - rsync
  - snapper
  - sqlite
  - tar
  - tree
  - tuned
  - tuned-ppd
  - zram-generator-defaults
  - zstd
  - brightnessctl # applications for windowmanager
  - fontawesome-fonts-all
  - gnome-keyring
  - gnome-keyring-pam
  - google-noto-emoji-fonts
  - kitty
  - material-icons-fonts
  - playerctl
  - wofi
  - xdg-desktop-portal-gnome
  - xwayland-satellite
  - matugen-git # copr
  - niri-git
  - quickshell-git
  - waypipe-git
  - yolk-git

packages_rpmfusion_package_state: skip

packages_copr_repos:
  - name: "giftpilz0/misc"
    state: "enabled"
