---
######################################
### vars

# - name: Set vars
#   hosts: workstation
#   vars_prompt:
#     - name: user_username
#       prompt: Select username
#       private: false
#     - name: user_password
#       prompt: Select password
#       private: true
#       confirm: true
#       unsafe: true
#   tasks:
#     - name: Set facts
#       ansible.builtin.set_fact:
#         user_username: "{{ user_username }}"
#         user_password: "{{ user_password }}"

- name: Load variables
  hosts: all
  tasks:
    - name: "Check if variables file exists"
      ansible.builtin.stat:
        path: "vars/{{ group_names[0] }}/{{ ansible_os_family }}.yml"
      register: vars_file
    - name: "Load variables file"
      ansible.builtin.include_vars: "vars/{{ group_names[0] }}/{{ ansible_os_family }}.yml"
      when: vars_file.stat.exists

######################################
### roles

- name: Configure hosts - common
  hosts: all
  roles:
    - role: giftpilz0.general.update
    - role: giftpilz0.general.packages
    - role: giftpilz0.general.timezone
    - role: giftpilz0.general.git
    - role: giftpilz0.general.sysutil

- name: Configure hosts - workstation
  hosts: workstation
  roles:
    - name: giftpilz0.general.autoupgrade
    - role: giftpilz0.general.firewalld
    # - role: giftpilz0.general.user
