---
name: Ansible lint

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Install dependencies
        run: |
          pip install ansible ansible-lint

      - name: Install Ansible collections
        run: |
          ansible-galaxy collection install "git+https://github.com/Giftpilz0/homelab.git#/ansible_collections/giftpilz0/general"
          ansible-galaxy collection install "git+https://github.com/Giftpilz0/homelab.git#/ansible_collections/giftpilz0/server"

      - name: Lint playbook
        run: |
          ansible-lint
